cookies

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -89,7 +89,7 @@ jobs:
           pipx inject yt-dlp "$WHL_FILE"
           pipx install "$WHL_FILE"
           # pip install ytdlp-jsc --no-index --find-links=./target/wheels/
-          # pip install ytdlp-jsc --no-index --find-links=./target/wheels/ --target=$PLUGIN_DIR
+          pip install ytdlp-jsc --no-index --find-links=./target/wheels/ --target=$PLUGIN_DIR
           pip install ytdlp-jsc --no-index --find-links=./target/wheels/ --target=./whl
 
           pyinstaller whl/ytdlp_jsc/cli.py --onedir --collect-all ytdlp_jsc
@@ -98,9 +98,11 @@ jobs:
           # ln -sf "$(pwd)/dist/cli/cli" ~/.ei/ytdlp-jsc-cli
           cp -rf dist/cli/cli ~/.ei/ytdlp-jsc-cli
           cp -rf dist/cli/_internal ~/.ei/_internal
-
-          yt-dlp -v --extractor-args "youtube:jsc_trace=true" -F "https://www.youtube.com/watch?v=E2Rj2gQAyPA" 2>&1 | grep -E "(jsc|Provider|challenge)" || echo "Command failed, continuing..."
-          yt-dlp -F "https://www.youtube.com/watch?v=E2Rj2gQAyPA" || echo "Command failed, continuing..."
+      - name: test
+        run:
+          echo ${{ secrets.YT_COOKIE }} > cookie.txt
+          yt-dlp --cookies cookies.txt -v --extractor-args "youtube:jsc_trace=true" -F "https://www.youtube.com/watch?v=E2Rj2gQAyPA" 2>&1 | grep -E "(jsc|Provider|challenge)" || echo "Command failed, continuing..."
+          yt-dlp --cookies cookies.txt -F "https://www.youtube.com/watch?v=E2Rj2gQAyPA" || echo "Command failed, continuing..."
       - name: install hyperfine
         run: |
           ei https://github.com/sharkdp/hyperfine
